language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

env:
  - GO111MODULE=on

install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - golint -set_exit_status ./...
  - go test -cover -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
